### ISSUE TITLE
Issue on the "Lectures, Tutorials and Webinars" webpage

### ISSUE THREAD

**Issue by SophieMacadamia** [IS-ENES3/IS-ENES-Website#9]
Hi Vi, I have an issue with the page "Lectures, Tutorials and Webinars". I have changed a bit the order of each video (organised in webinar/training/whorkshop/school) and I must have made a mistake because I received an error message. Can you please have a look ? Thank you !

**Comment by valeriupredoi** [comment]
hi @SophieMacadamia @fannyadloff I have now fixed it and it works as it used to https://is.enes.org/lectures-tutorials-webinars/

The reason why it showed a 404 was that the html page was not built due to a compilation issue from the Markdown https://raw.githubusercontent.com/IS-ENES3/IS-ENES-Website/main/pages/lectures-tutorials-webinars.md and the issue with the Markdown was that Sophie added strings followed by colons, but did not encase them in quotes eg `text: WEBINAR: Introduction to ESMValTool (June 2022). 1 hour video.` - colons are key separators in Markdown so if the text that contains them is not encased in "" then the compiler will interpret them dynamical elements, just like in a Python dictionary `dict = {a: 2, b: 3}`. So next time, put all the text that is supposed to be text on the site in quotes, pls, Sophie, in these cases :beer:
